#ifndef KEYS_H
#define KEYS_H

/*12-bit tuning of each key in octaves 1-8 (from pg38 of YM2149 documentation)*/

/*no sound*/
#define REST 0x0000

/*octave 1*/
#define C1_KEY 0x0D5D
#define C1_SHARP_KEY 0x0C9C
#define D1_FLAT_KEY 0x0C9C
#define D1_KEY 0x0BE7
#define D1_SHARP_KEY 0x0B3C
#define E1_FLAT_KEY 0x0B3C
#define E1_KEY 0x0A9B
#define F1_KEY 0x0A02
#define F1_SHARP_KEY 0x0973
#define G1_FLAT_KEY 0x0973
#define G1_KEY 0x08EB
#define G1_SHARP_KEY 0x086B
#define A1_FLAT_KEY 0x086B
#define A1_KEY 0x07F2
#define A1_SHARP_KEY 0x0780
#define B1_FLAT_KEY 0x0780
#define B1_KEY 0x0714

/*octave 2*/
#define C2_KEY 0x06AE
#define C2_SHARP_KEY 0x064E
#define D2_FLAT_KEY 0x064E
#define D2_KEY 0x05F4
#define D2_SHARP_KEY 0x059E
#define E2_FLAT_KEY 0x059E
#define E2_KEY 0x054D
#define F2_KEY 0x0501
#define F2_SHARP_KEY 0x04B9
#define G2_FLAT_KEY 0x04B9
#define G2_KEY 0x0475
#define G2_SHARP_KEY 0x0435
#define A2_FLAT_KEY 0x0435
#define A2_KEY 0x03F9
#define A2_SHARP_KEY 0x03C0
#define B2_FLAT_KEY 0x03C0
#define B2_KEY 0x038A

/*octave 3*/
#define C3_KEY 0x0357
#define C3_SHARP_KEY 0x0327
#define D3_FLAT_KEY 0x0327
#define D3_KEY 0x02FA
#define D3_SHARP_KEY 0x02CF
#define E3_FLAT_KEY 0x02CF
#define E3_KEY 0x02A7
#define F3_KEY 0x0281
#define F3_SHARP_KEY 0x025D
#define G3_FLAT_KEY 0x025D
#define G3_KEY 0x023B
#define G3_SHARP_KEY 0x021B
#define A3_FLAT_KEY 0x021B
#define A3_KEY 0x01FC
#define A3_SHARP_KEY 0x01E0
#define B3_FLAT_KEY 0x01E0
#define B3_KEY 0x01C5

/*octave 4*/
#define C4_KEY 0x01AC
#define C4_SHARP_KEY 0x0194
#define D4_FLAT_KEY 0x0194
#define D4_KEY 0x017D
#define D4_SHARP_KEY 0x0168
#define E4_FLAT_KEY 0x0168
#define E4_KEY 0x0153
#define F4_KEY 0x0140
#define F4_SHARP_KEY 0x012E
#define G4_FLAT_KEY 0x012E
#define G4_KEY 0x011D
#define G4_SHARP_KEY 0x010D
#define A4_FLAT_KEY 0x010D
#define A4_KEY 0x00FE
#define A4_SHARP_KEY 0x00F0
#define B4_FLAT_KEY 0x00F0
#define B4_KEY 0x00E2

/*octave 5*/
#define C5_KEY 0x00D6
#define C5_SHARP_KEY 0x00CA
#define D5_FLAT_KEY 0x00CA
#define D5_KEY 0x00BE
#define D5_SHARP_KEY 0x00B4
#define E5_FLAT_KEY 0x00B4
#define E5_KEY 0x00AA
#define F5_KEY 0x00A0
#define F5_SHARP_KEY 0x0097
#define G5_FLAT_KEY 0x0097
#define G5_KEY 0x008F
#define G5_SHARP_KEY 0x0087
#define A5_FLAT_KEY 0x0087
#define A5_KEY 0x007F
#define A5_SHARP_KEY 0x0078
#define B5_FLAT_KEY 0x0078
#define B5_KEY 0x0071

/*octave 6*/
#define C6_KEY 0x006B
#define C6_SHARP_KEY 0x0065
#define D6_FLAT_KEY 0x0065
#define D6_KEY 0x005F
#define D6_SHARP_KEY 0x005A
#define E6_FLAT_KEY 0x005A
#define E6_KEY 0x0055
#define F6_KEY 0x0050
#define F6_SHARP_KEY 0x004C
#define G6_FLAT_KEY 0x004C
#define G6_KEY 0x0047
#define G6_SHARP_KEY 0x0043
#define A6_FLAT_KEY 0x0043
#define A6_KEY 0x0040
#define A6_SHARP_KEY 0x003C
#define B6_FLAT_KEY 0x003C
#define B6_KEY 0x0039

/*octave 7*/
#define C7_KEY 0x0035
#define C7_SHARP_KEY 0x0032
#define D7_FLAT_KEY 0x0032
#define D7_KEY 0x0030
#define D7_SHARP_KEY 0x002D
#define E7_FLAT_KEY 0x002D
#define E7_KEY 0x002A
#define F7_KEY 0x0028
#define F7_SHARP_KEY 0x0026
#define G7_FLAT_KEY 0x0026
#define G7_KEY 0x0024
#define G7_SHARP_KEY 0x0022
#define A7_FLAT_KEY 0x0022
#define A7_KEY 0x0020
#define A7_SHARP_KEY 0x001E
#define B7_FLAT_KEY 0x001E
#define B7_KEY 0x001C

/*octave 8*/
#define C8_KEY 0x001B
#define C8_SHARP_KEY 0x0019
#define D8_FLAT_KEY 0x0019
#define D8_KEY 0x0018
#define D8_SHARP_KEY 0x0016
#define E8_FLAT_KEY 0x0016
#define E8_KEY 0x0015
#define F8_KEY 0x0014
#define F8_SHARP_KEY 0x0013
#define G8_FLAT_KEY 0x0013
#define G8_KEY 0x0012
#define G8_SHARP_KEY 0x0011
#define A8_FLAT_KEY 0x0011
#define A8_KEY 0x0010
#define A8_SHARP_KEY 0x000F
#define B8_FLAT_KEY 0x000F
#define B8_KEY 0x000E

#endif